### ISSUE TITLE
QUIC support?

### ISSUE THREAD

**Issue by DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K** [facebookexperimental/doh-proxy#10]
Any plans to support QUIC with http/2?

**Comment by chantra** [comment]
@DtpEJsaYXDU4GDH8dE4MyI9VrieF0UZpPZ0K76K 

nope, this is aiming at implementing https://datatracker.ietf.org/doc/draft-ietf-doh-dns-over-https/ and QUIC is not covered currently.
