### ISSUE TITLE
Enhancement to support ECH standard for SNI

### ISSUE THREAD

**Issue by FrixosTh** [facebookexperimental/doh-proxy#101]
Dear Team,

Thanks for the amazing work you put into doh-proxy! It has been an integral part of our network structure! We were using doh-proxy for ESNI among others extensively. However Firefox and Cloudflare are removing support for ESNI in favor of the new ECH standard. I know it's really early on the specifications of the protocol but I would like to know if this is something you are looking into and upgrading doh-proxy to support ECH?

Thanks in advance for taking the time to consider this.
Best Regards

**Comment by chantra** [comment]
Hi @FrixosTh,

There is no plan to implement ECH in DoH Proxy at this stage, albeit it should be possible assuming the openssl library used in the environment supports TLS1.3 and code change would likely be in https://github.com/facebookexperimental/doh-proxy/blob/e24032d40fa61bb49a56a8301ff0221016372aba/dohproxy/utils.py#L107-L148

A reverse proxy fronting dohproxy, would be in a good position to do that in the future once it gets implemented by those.

If implementing it in dohproxy seems simple enough (I have not looked at what it would take to support ECH), a PR would be welcome though.
