### ISSUE TITLE
POST support in doh-httpproxy?

### ISSUE THREAD

**Issue by jedisct1** [facebookexperimental/doh-proxy#12]
Hi!

Would it be possible to support `POST` requests in `httpproxy`? That would be great!

I naively tried to add a route, but I'm not familiar with aiohttp and reading the body seems to be a bit trickier.

**Comment by chantra** [comment]
I will check it out. I may have missed that step when I copy/pasta-e le it from doh-proxy

**Comment by chantra** [comment]
So this should have made it in v0.0.5 but apparently I messed up the pip package and it was not included as part of the packaging.
I will release a 0.0.6 version soon which will include it.
