### ISSUE TITLE
[Feat] Add an option to change upstream port number

### ISSUE THREAD

**Issue by publicarray** [facebookexperimental/doh-proxy#16]
https://github.com/facebookexperimental/doh-proxy/blob/e5714f94fdbbfb3f4c6d937fc87f5712e849325b/dohproxy/httpproxy.py#L71

**Comment by chantra** [comment]
Hi @publicarray 
This should be pretty easy to hack into for both `httpproxy` and the h2 `proxy`.
PR welcomed though 😄

**Comment by publicarray** [comment]
Thank you! 👍
