### ISSUE TITLE
Scheme should be https

### ISSUE THREAD

**Issue by dknecht** [facebookexperimental/doh-proxy#17]
https://github.com/facebookexperimental/doh-proxy/blob/c5d0d4a03da38a5f2c36282b2c37923b7aa2dc89/dohproxy/protocol.py#L134

 https://tools.ietf.org/html/rfc7540#section-8.1.2.3
> The ":scheme" pseudo-header field includes the scheme portion of the target URI ([RFC3986], Section 3.1).

It currently fails for doh-client  --domain dns.cloudflare.com  --qname www.cloudflare.com  --debug --post because we are doing strict validation.

**Comment by chantra** [comment]
Thanks @dknecht I will look into fixing it when times allows. If you have a local fix, PR is welcomed :)

**Comment by dknecht** [comment]
Thanks.  You beat me to it.
