### ISSUE TITLE
[doh-httpproxy] --trusted mandatory ?

### ISSUE THREAD

**Issue by pettai** [facebookexperimental/doh-proxy#50]
Hi, 
After upgrading to latest version in pip to get the new draft-13 compliance (that's needed for Firefox =<62 it seems), doh-httpproxy starts up as usual, but no longer want to serve DOH queries with error message: 

```
2018-10-03 13:32:08,515:    ERROR: Too many X-Forwarded-For values: [IPv4Address('127.0.0.1')], expected 2
2018-10-03 13:37:36,262:    ERROR: Too many X-Forwarded-For values: [IPv4Address('127.0.0.1')], expected 2
```

Is `--trusted` mandatory now? (If I supply that, it starts working as normal) https://github.com/facebookexperimental/doh-proxy/pull/49
Anyway, I think 127.0.0.1 and ::1 are sane defaults even without having to supply `--trusted`

**Comment by chantra** [comment]
Hi,

This is because your reverse proxy is not setting x-forwarded-for. I suppose the error message could be better...

**Comment by pettai** [comment]
Ah, got it
