### ISSUE TITLE
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

### ISSUE THREAD

**Issue by Warok21** [facebookexperimental/doh-proxy#53]
I used the following command to create my private and public key : 

`openssl req -newkey rsa:2048 -nodes -keyout doh.key -x509 -days 365 -out doh.pem`

And used this command to run doh-proxy(160.98.31.165 is the IP of my server)
`sudo doh-proxy --upstream-resolver=1.1.1.1 --certfile=/home/adriano/projet/doh.pem --keyfile=/home/adriano/projet/doh.key --listen-address=160.98.31.165
`

When I try to make a request with doh-client : 
`sudo doh-client --qname heai-fr.ch --domain 160.98.31.165`
I get the this error:

> ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645)

When I try to check my SSL connection, with:
`openssl s_client -connect 160.98.31.165:443`
It works
Does anybody know how to fix the error?

**Comment by chantra** [comment]
so... `--insecure` is not "publicly" documented. And I don't think it should. Really certificates are easy to go by these days. For people using their own CA, there is `--cafile` option.
