### ISSUE TITLE
Request stuck

### ISSUE THREAD

**Issue by Warok21** [facebookexperimental/doh-proxy#54]
I used this command to run my doh-server:
`sudo doh-proxy --upstream-resolver=1.1.1.1 --certfile=/../fullchain.pem --keyfile=/etc/.../privkey.pem --listen-address 160.98.31.165`
And I try with my client this one:
`sudo doh-client --qname 160.98.31.165 --domain heia-fr.ch`
But my request is stuck like that : 

> 2018-12-18 18:01:15,388:    DEBUG: Opening connection to heia-fr.ch
> 2018-12-18 18:01:15,443:    DEBUG: Query parameters: {'dns': 'AAABAAABAAAAAAAAAzE2MAI5OAIzMQMxNjUAABwAAQ'}
> 2018-12-18 18:01:15,445:    DEBUG: Stream ID: 1 / Total streams: 0

And I can wait for ever.
Can anyone help me?
Thanks

**Comment by chantra** [comment]
Qname should be what you are querying for. Domain is the TLS domain. So
swap those 2. Currently your request is being sent to heia-fr.ch which is
most likely not understanding http2/DoH.

Is the DoH-client help inaccurate? Can you send a PR to fix it if this is
the case.

**Comment by rctl** [comment]
Might I suggest swapping `--domain` with `--endpoint` as the word domain seems to cause confusion...

**Comment by chantra** [comment]
@rctl I don;t have strong opinions. Be it to update the documentation or change the flag. Changing the flag means that the old one needs to be kept along for backward compatibility (albeit hidden) and that the code needs to be updated to reflect flag name. This is used by both `doh-client` and `doh-stub`. I favor documentation update. PR would be welcome. 

```
$ doh-client --help
usage: doh-client [-h] [--domain DOMAIN] [--uri URI]
                  [--remote-address REMOTE_ADDRESS] [--port PORT] [--post]
                  [--debug] [--level LEVEL] [--cafile CAFILE] [--version]
                  [--qname QNAME] [--qtype QTYPE] [--dnssec]

optional arguments:
  -h, --help            show this help message and exit
  --domain DOMAIN       Domain to make DOH request against. Default:
                        [localhost]
  --uri URI             DNS API URI. Default [/dns-query]
  --remote-address REMOTE_ADDRESS
                        Remote address where the DOH proxy is running. If
                        None, --domain will be resolved to lookup and IP.
                        Default: [None]
  --port PORT           Port to connect to. Default: [443]
  --post                Use HTTP POST instead of GET.
  --debug               Prints some debugging output
  --level LEVEL         log level [DEBUG]
  --cafile CAFILE       Specify custom CA file for cert verification
  --version             show program's version number and exit
  --qname QNAME         Name to query for. Default [example.com]
  --qtype QTYPE         Type of query. Default [AAAA]
  --dnssec              Enable DNSSEC validation.
```
