### ISSUE TITLE
doh-stub mode Runtime error

### ISSUE THREAD

**Issue by WakamizuLee** [facebookexperimental/doh-proxy#55]
Hello, I observed the log. Occasionally, after a few days of running, there will be such a warning, and the connection will be cut off.
<<ERROR: Fatal read error on socket transport>>
Query the next google, most people say it is a problem with python itself.
What do you think?
I hope you can check this question, thank you!

**Comment by WakamizuLee** [comment]
In the next hour, the following two logs are generated.
(1)WARNING: Remote peer sent GOAWAY [ERR: ErrorCodes.NO_ERROR], disconnect now.
(2)ERROR: Task was destroyed but it is pending!
The first one is often there, but it works fine.

**Comment by WakamizuLee** [comment]
Two more log records appeared after the next clock. The first one was recurring, and the second one was seen for the first time.
(1)WARNING: Remote peer sent GOAWAY [ERR: ErrorCodes.NO_ERROR], disconnect now.
(2)ERROR: Task was destroyed but it is pending!
I hope to get your reference.

**Comment by chantra** [comment]
Hi, I don’t believe any of those errors prevent the proxy from working
right?

**Comment by WakamizuLee** [comment]
Thank you for checking my information.
The connection really broke for about two minutes.
Is this an accidental running error in the program, or is it caused by the Internet vendor's tentative blocking port behavior?

**Comment by WakamizuLee** [comment]
I mean the error that is read will affect the work.

**Comment by WakamizuLee** [comment]
Ok, thank you for your review and recovery. I will observe it for a while. There are not too many error logs to refer to.
If there is new progress, I will contact you again.Thank you!

**Comment by chantra** [comment]
@WakamizuLee I am going to close this issue. If you have more detail, please open a new issue.
