### ISSUE TITLE
[httpproxy] loglevel (--level) is ignored in some parts of the code

### ISSUE THREAD

**Issue by appliedprivacy** [facebookexperimental/doh-proxy#57]
When setting the loglevel to ERROR via `--level ERROR` INFO level logs entries are still written in the two locations bellow:

https://github.com/facebookexperimental/doh-proxy/blob/149c97de56d193241ba6ca8c5a822d10720d0d98/dohproxy/server_protocol.py#L87

https://github.com/facebookexperimental/doh-proxy/blob/149c97de56d193241ba6ca8c5a822d10720d0d98/dohproxy/server_protocol.py#L112

https://github.com/facebookexperimental/doh-proxy/blob/149c97de56d193241ba6ca8c5a822d10720d0d98/dohproxy/server_protocol.py#L122

**Comment by chantra** [comment]
The logger in that class is hard coded to ‘DEBUG’. It should/may be trivial to initialize it based on the level specified at the CLI. PR welcome :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by chantra** [comment]
this should be fixed with #58

**Comment by chantra** [comment]
v0.0.9, which contains the fix, was pushed to pip
