### ISSUE TITLE
Python 3.7 support?

### ISSUE THREAD

**Issue by publicarray** [facebookexperimental/doh-proxy#63]
```sh
~ ❯ python3 --version
Python 3.7.3
~ ❯  doh-client --domain doh.seby.io --port 8443 --qname example.com --qtype A
Traceback (most recent call last):
  File "/usr/local/bin/doh-client", line 6, in <module>
    from dohproxy.client import main
  File "/usr/local/lib/python3.7/site-packages/dohproxy/client.py", line 12, in <module>
    from dohproxy import client_protocol, utils
  File "/usr/local/lib/python3.7/site-packages/dohproxy/client_protocol.py", line 10, in <module>
    import aioh2
  File "/usr/local/lib/python3.7/site-packages/aioh2/__init__.py", line 2, in <module>
    from .helper import *
  File "/usr/local/lib/python3.7/site-packages/aioh2/helper.py", line 89
    async_task = asyncio.async
                             ^
SyntaxError: invalid syntax
```

A quick search brought me here: https://github.com/riptideio/pymodbus/issues/319

**Comment by chantra** [comment]
This exception is raised from within aioh2. It seems to be fixed upstream
but no new package was pushed:
https://github.com/decentfox/aioh2/commit/e8105131ac13817f9d8dd432e2827a736085c69f

Can you install aioh2 from master?

**Comment by chantra** [comment]
@publicarray I will close this under the assumption that this is fixed when using aioh2 master branch. If this is the case, you may want to ping them to cut a new release.

**Comment by chantra** [comment]
For anyone having this issue, I believe:
```
pip install git+https://github.com/decentfox/aioh2.git 
```
should help installing off master and supposedly fix this issue.

**Comment by laggardkernel** [comment]
aioh2 is dead. The last commit is in 2018.
