### ISSUE TITLE
[doh-httpproxy] logging to a file option?

### ISSUE THREAD

**Issue by brittanywang** [facebookexperimental/doh-proxy#71]
I wondering if there was an option where you can log the output of what you see when you run `doh-httpproxy` on the command line to a .log file? 
![logging](https://user-images.githubusercontent.com/35832643/67323840-da523280-f4c7-11e9-91e2-3a9a39783ad3.png)

**Comment by chantra** [comment]
@brittanywang wouldn't steam redirecting stdout/stderr to a file work just fine?

**Comment by chantra** [comment]
@brittanywang 
I think file redirection should go a long way for what you need. You could also use `tee` if you want it both to stderr and a file.
When using systemd, the stderr stream is automatically sent to the logs.

I will close this issue for now as there is existing mechanism in place to solve this problem. Feel free to open another one if you have any other issues.
