### ISSUE TITLE
doh-stub & doh-client crash on Debian 10

### ISSUE THREAD

**Issue by rsenger2** [facebookexperimental/doh-proxy#72]
While doh-httpproxy runs fine on Debian 10, both doh-stub and doh-client crash with this error:

`root@alkurah:~# doh-stub
Traceback (most recent call last):
  File "/usr/local/bin/doh-stub", line 6, in <module>
    from dohproxy.stub import main
  File "/usr/local/lib/python3.7/dist-packages/dohproxy/stub.py", line 11, in <module>
    from dohproxy import client_protocol, utils
  File "/usr/local/lib/python3.7/dist-packages/dohproxy/client_protocol.py", line 10, in <module>
    import aioh2
  File "/usr/local/lib/python3.7/dist-packages/aioh2/__init__.py", line 2, in <module>
    from .helper import *
  File "/usr/local/lib/python3.7/dist-packages/aioh2/helper.py", line 89
    async_task = asyncio.async
                             ^
SyntaxError: invalid syntax
`
Installation was successful:
`root@alkurah:~# pip3 install doh-proxy
Collecting doh-proxy
  Using cached https://files.pythonhosted.org/packages/46/eb/e6aab2f014069f5e136fe1e3ce82928a5ab2ab17b7ab54a129e7a8f8ee04/doh_proxy-0.0.9-py3-none-any.whl
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/dist-packages (from doh-proxy) (1.16.0)
Requirement already satisfied: aiohttp>=2.3.0 in /usr/local/lib/python3.7/dist-packages (from doh-proxy) (3.6.2)
Requirement already satisfied: aioh2>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from doh-proxy) (0.2.2)
Requirement already satisfied: aiohttp-remotes>=0.1.2 in /usr/local/lib/python3.7/dist-packages (from doh-proxy) (0.1.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=2.3.0->doh-proxy) (1.3.0)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=2.3.0->doh-proxy) (3.0.1)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/lib/python3/dist-packages (from aiohttp>=2.3.0->doh-proxy) (3.0.4)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=2.3.0->doh-proxy) (19.3.0)
Requirement already satisfied: multidict<5.0,>=4.5 in /usr/local/lib/python3.7/dist-packages (from aiohttp>=2.3.0->doh-proxy) (4.5.2)
Requirement already satisfied: h2<4,>=3 in /usr/local/lib/python3.7/dist-packages (from aioh2>=0.2.1->doh-proxy) (3.1.1)
Requirement already satisfied: priority==1.3.0 in /usr/local/lib/python3.7/dist-packages (from aioh2>=0.2.1->doh-proxy) (1.3.0)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp>=2.3.0->doh-proxy) (2.6)
Requirement already satisfied: hpack<4,>=2.3 in /usr/local/lib/python3.7/dist-packages (from h2<4,>=3->aioh2>=0.2.1->doh-proxy) (3.0.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.7/dist-packages (from h2<4,>=3->aioh2>=0.2.1->doh-proxy) (5.2.0)
Installing collected packages: doh-proxy
Successfully installed doh-proxy-0.0.9
`

**Comment by rsenger2** [comment]
Sorry for the layout, don't know how to format this...

**Comment by chantra** [comment]
@rsenger2  you may want to bump https://github.com/decentfox/aioh2/issues/21 as this is why the failure is happening.
Alternatively, force pip to install from master. I believe something like:
```
pip install git+https://github.com/decentfox/aioh2.git 
```

There is nothing really actionable on doh-proxy side so I will go ahead and close this task.
