### ISSUE TITLE
asyncio.async invalid syntax error

### ISSUE THREAD

**Issue by listenfree** [facebookexperimental/doh-proxy#73]
run in python3.7 alpine docker,

/ # doh-stub
Traceback (most recent call last):
  File "/usr/local/bin/doh-stub", line 5, in <module>
    from dohproxy.stub import main
  File "/usr/local/lib/python3.7/site-packages/dohproxy/stub.py", line 11, in <module>
    from dohproxy import client_protocol, utils
  File "/usr/local/lib/python3.7/site-packages/dohproxy/client_protocol.py", line 10, in <module>
    import aioh2
  File "/usr/local/lib/python3.7/site-packages/aioh2/__init__.py", line 2, in <module>
    from .helper import *
  File "/usr/local/lib/python3.7/site-packages/aioh2/helper.py", line 89
    async_task = asyncio.async
                             ^
SyntaxError: invalid syntax

**Comment by listenfree** [comment]
/ # pip3 install doh-proxy
Requirement already satisfied: doh-proxy in /usr/local/lib/python3.7/site-packages (0.0.9)
Requirement already satisfied: dnspython in /usr/local/lib/python3.7/site-packages (from doh-proxy) (1.16.0)
Requirement already satisfied: aiohttp-remotes>=0.1.2 in /usr/local/lib/python3.7/site-packages (from doh-proxy) (0.1.2)
Requirement already satisfied: aioh2>=0.2.1 in /usr/local/lib/python3.7/site-packages (from doh-proxy) (0.2.2)
Requirement already satisfied: aiohttp>=2.3.0 in /usr/local/lib/python3.7/site-packages (from doh-proxy) (3.6.2)
Requirement already satisfied: priority==1.3.0 in /usr/local/lib/python3.7/site-packages (from aioh2>=0.2.1->doh-proxy) (1.3.0)
Requirement already satisfied: h2<4,>=3 in /usr/local/lib/python3.7/site-packages (from aioh2>=0.2.1->doh-proxy) (3.2.0)
Requirement already satisfied: yarl<2.0,>=1.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->doh-proxy) (1.4.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->doh-proxy) (19.3.0)
Requirement already satisfied: chardet<4.0,>=2.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->doh-proxy) (3.0.4)
Requirement already satisfied: multidict<5.0,>=4.5 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->doh-proxy) (4.7.4)
Requirement already satisfied: async-timeout<4.0,>=3.0 in /usr/local/lib/python3.7/site-packages (from aiohttp>=2.3.0->doh-proxy) (3.0.1)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python3.7/site-packages (from h2<4,>=3->aioh2>=0.2.1->doh-proxy) (3.0.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /usr/local/lib/python3.7/site-packages (from h2<4,>=3->aioh2>=0.2.1->doh-proxy) (5.2.0)
Requirement already satisfied: idna>=2.0 in /usr/local/lib/python3.7/site-packages (from yarl<2.0,>=1.0->aiohttp>=2.3.0->doh-proxy) (2.9)

**Comment by chantra** [comment]
This is the same issue as #63 . I don’t think upstream has released any new version yet. If you install aioh2 from master, this issue should not happen anymore.
