### ISSUE TITLE
doh-stub does not work on Windows 10

### ISSUE THREAD

**Issue by DissectMalware** [facebookexperimental/doh-proxy#74]
I am trying to use doh-stub to relay DNS traffic to Cloudflare (or any other DoH provider) using the following command:
doh-stub --listen-port 5553 --listen-address 127.0.0.1 --domain cloudflare-dns.com

and trying to test it using nslookup:
nslookup -port=5553 google.com 127.0.0.1

I am getting:
*** UnKnown can't find google.com: No response from server

No firewall rule, No EDR, No Antivirus, ... . However, it seems the doh-stub does not listening to the port; thus not responding.

OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.17134 N/A Build 17134

Python 3.6.4

I tried on another system (same OS and python), same result.

I used the following command to install:
pip install doh-proxy

**Comment by chantra** [comment]
You are telling DoH-stub to listen on ::1, yet you are telling nslookup to query a server at 127.0.0.1 . Things may get much better if you tell it to query the server at the address it is listening on.

**Comment by chantra** [comment]
Oh you updated the description to match the address.
I have no experience troubleshooting windows, that being said, you mention 

> However, it seems the doh-stub does not listening to the port; thus not responding.

What is it listening on? Can you find that out?
If you were to connect using TCP to the address/port DoH-stub is supposed to be listening on, do you get a connection? What does tcpdump shows if this is not happening?
Have you tried enabling debug logging? Anything interesting? Could you paste those logs in the issue report?
Have you tried using DoH-client directly against Cloudflare to see if it can resolve? What is the outcome? This would confirm whether or not the query path is properly set for instance.

**Comment by chantra** [comment]
@DissectMalware I did not hear back from you and will close this issue. Hopefully the few questions I asked will help you getting to the bottom of it.
If you find a solution, please comment back here, it may help the next person stumbling on this issue.
