### ISSUE TITLE
Queries made with doh-client lack accept header?

### ISSUE THREAD

**Issue by complex2d** [facebookexperimental/doh-proxy#94]
https://github.com/facebookexperimental/doh-proxy/blob/85df602d01c5ddf514a92f23b19a65c17aa73a56/dohproxy/client_protocol.py#L105

If I'm reading this right, headers at the line above is overwritten a few lines below at line 111.
I moved the accept header to down to headers.extend at line 123, and it appears to resolve the issue.

        headers.extend([
            ('accept', constants.DOH_MEDIA_TYPE),
            ('content-length', str(len(body))),
        ])

**Comment by chantra** [comment]
@complex2d yeah, it seems line 105 is just history.

I think it could be moved directly into https://github.com/facebookexperimental/doh-proxy/blob/85df602d01c5ddf514a92f23b19a65c17aa73a56/dohproxy/client_protocol.py#L111-L115
