### ISSUE TITLE
connection timeout for TCP queries

### ISSUE THREAD

**Issue by crolfe** [facebookexperimental/doh-proxy#99]
Hi there!

I noticed that `try_tcp` in dohproxy/server_protocol.py does not set a timeout when attempting create a connection with the configured resolver.  Should the configured resolver be in a state where it is not accepting TCP connections, then it is possible that requests could be stuck waiting indefinitely for a connection to be established.  This appears to be easy enough to resolve if we wrap `create_connection` with `asyncio.wait_for`, and use the existing timeout value.

If this is a change you are interested in, please let me know and I will send a PR.

**Comment by chantra** [comment]
Hi @crolfe ,

Thanks! Could you point out any specific code path? Is this on a specific version? The query should be wrapped in a timer: https://github.com/facebookexperimental/doh-proxy/blob/52648030edd3a76a33f005a3bda3403d2e36f235/dohproxy/server_protocol.py#L73-L93

**Comment by crolfe** [comment]
The following tests were run against the latest commit in master (`5264803`)

I start a server pointed at an arbitrary local IP that is *not* listening on port 53 to act as my upstream resolver: 
```
python3 dohproxy/httpproxy.py --trusted --upstream-resolver 192.168.2.10 --listen-address 127.0.0.1 --port 8000
```

With a  DEFAULT_TIMEOUT of 10 seconds on the DNSClient, I would expect to see a request timeout after ~20 seconds (10 seconds to try UDP, 10 seconds to try TCP, plus a little request/response overhead).  

However, the following command shows a request that well exceeds the expected timeout:
```
> curl http://127.0.0.1:8000/dns-query\?dns\=gCsBAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE -I -w "%{time_total}" --max-time 30

curl: (28) Operation timed out after 30001 milliseconds with 0 bytes received
30.001918
``` 

If I wrap line 77 above in an `asyncio.wait_for`, then I see my expected 20 second timeout (and I get a SERFAIL response back):
```
> curl http://127.0.0.1:8000/dns-query\?dns\=gCsBAAABAAAAAAAAB2V4YW1wbGUDY29tAAABAAE -I -w "%{time_total}" --max-time 30

HTTP/1.1 200 OK
Content-Type: application/dns-message
Content-Length: 0
Date: Thu, 04 Feb 2021 01:18:07 GMT
Server: Python/3.8 aiohttp/3.7.3

20.026066%
```

My try_tcp function looks like this:

```
    async def query_tcp(self, dnsq, clientip, timeout=DEFAULT_TIMEOUT):
        qid = dnsq.id
        fut = asyncio.Future()
        try:
            transport, _ = await asyncio.wait_for(
                self.loop.create_connection(
                    lambda: DNSClientProtocolTCP(
                        dnsq, fut, clientip, logger=self.logger
                    ),
                    self.upstream_resolver,
                    self.upstream_port,
                ),
                timeout,
            )
        except asyncio.TimeoutError:
            # Failed to connect to the resolver
            return None

        return await self._try_query(fut, qid, timeout, transport)
```

Hope that helps!

**Comment by chantra** [comment]
ha yeah, only the query itself (once the connection is established) is wrapper in the `wait_for`. In you case, creating the connection itself is what is timing out.

[create_connection](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.create_connection) does not seem to have any timeout parameter (aside form the ssl one), so your approach is probably the way to go.

Do you mind providing a patch? The minor nit would be to add a debug like with a line along: "Timeout connecting to upstream resolver {}:{}".format(self.upstream_resolver, self.upstream_port).

Thanks
